### ISSUE TITLE
rake rbs:activesupport:setup fails when there is a constant declaration like the following in the included block of AS::Concern.

### ISSUE THREAD

**Issue by fumihumi** [tk0miya/rbs_activesupport#50]
The following test can be used to reproduce this error after v1.3.0... 

```ruby
diff --git a/spec/rbs_acrtivesupport/parser_spec.rb b/spec/rbs_acrtivesupport/parser_spec.rb
index 1f6178a..ceceb1a 100644
--- a/spec/rbs_acrtivesupport/parser_spec.rb
+++ b/spec/rbs_acrtivesupport/parser_spec.rb
@@ -551,5 +551,47 @@ RSpec.describe RbsActivesupport::Parser do
         expect(parser.method_calls.size).to eq 0
       end
     end
+
+    context "When the code contains included calls with dynamic constant definition" do
+      let(:code) do
+        <<~RUBY
+          module Foo
+            include Bar
+          end
+
+          module Bar
+            included do
+              self::XXX = "CONSTANTS".freeze
+            end
+          end
+        RUBY
+      end
+
+      it "does not raise an error" do
+        expect { subject }.not_to raise_error
+      end
+    end
   end
```

```
Failures:

  1) RbsActivesupport::Parser#parse When the code contains included calls with dynamic constant definition does not raise an error
     Failure/Error: expect { subject }.not_to raise_error
     
       expected no Exception, got RuntimeError with backtrace:
         # /Users/me/.local/share/mise/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/prototype/rb.rb:447:in `const_to_name!'
         # /Users/me/.local/share/mise/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/prototype/rb.rb:438:in `const_to_name!'
         # /Users/me/.local/share/mise/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/prototype/rb.rb:371:in `process'
         # ./lib/rbs_activesupport/parser.rb:95:in `process'
         # ./lib/rbs_activesupport/parser.rb:89:in `block in process'
         # ./lib/rbs_activesupport/parser.rb:116:in `with_included'
         # ./lib/rbs_activesupport/parser.rb:88:in `process'
```

It seems that if you declare a constant like self:DYNAMIC_CONST in an included block, you will get an error.
Is it possible to support this syntax in RbsActivesupport::Parser?

**Comment by tk0miya** [comment]
This is a bug of rbs.

```
$ cat app.rb
class Foo
  self::BAR = 1
end

p Foo
p Foo::BAR
```
```
$ ruby app.rb
Foo
1
```
```
$ bundle exec rbs prototype rb app.rb
bundler: failed to load command: rbs (/Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/bin/rbs)
/Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/prototype/rb.rb:447:in `const_to_name!': unhandled exception
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/prototype/rb.rb:438:in `const_to_name!'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/prototype/rb.rb:371:in `process'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/prototype/rb.rb:428:in `block in process_children'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/prototype/helpers.rb:91:in `block in each_node'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/prototype/helpers.rb:89:in `each'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/prototype/helpers.rb:89:in `each_node'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/prototype/helpers.rb:85:in `each_child'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/prototype/rb.rb:427:in `process_children'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/prototype/rb.rb:422:in `process'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/prototype/rb.rb:428:in `block in process_children'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/prototype/helpers.rb:91:in `block in each_node'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/prototype/helpers.rb:89:in `each'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/prototype/helpers.rb:89:in `each_node'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/prototype/helpers.rb:85:in `each_child'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/prototype/rb.rb:427:in `process_children'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/prototype/rb.rb:422:in `process'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/prototype/rb.rb:133:in `block in process'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/prototype/helpers.rb:91:in `block in each_node'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/prototype/helpers.rb:89:in `each'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/prototype/helpers.rb:89:in `each_node'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/prototype/rb.rb:132:in `process'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/prototype/rb.rb:428:in `block in process_children'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/prototype/helpers.rb:91:in `block in each_node'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/prototype/helpers.rb:89:in `each'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/prototype/helpers.rb:89:in `each_node'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/prototype/helpers.rb:85:in `each_child'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/prototype/rb.rb:427:in `process_children'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/prototype/rb.rb:422:in `process'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/prototype/rb.rb:428:in `block in process_children'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/prototype/helpers.rb:91:in `block in each_node'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/prototype/helpers.rb:89:in `each'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/prototype/helpers.rb:89:in `each_node'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/prototype/helpers.rb:85:in `each_child'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/prototype/rb.rb:427:in `process_children'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/prototype/rb.rb:422:in `process'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/prototype/rb.rb:104:in `parse'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/cli.rb:825:in `block in run_prototype_file'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/cli.rb:824:in `each'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/cli.rb:824:in `run_prototype_file'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/cli.rb:555:in `run_prototype'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/lib/rbs/cli.rb:140:in `run'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-3.6.1/exe/rbs:7:in `<top (required)>'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/bin/rbs:25:in `load'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/bin/rbs:25:in `<top (required)>'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/bundler-2.5.14/lib/bundler/cli/exec.rb:58:in `load'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/bundler-2.5.14/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/bundler-2.5.14/lib/bundler/cli/exec.rb:23:in `run'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/bundler-2.5.14/lib/bundler/cli.rb:455:in `exec'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/bundler-2.5.14/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/bundler-2.5.14/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/bundler-2.5.14/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/bundler-2.5.14/lib/bundler/cli.rb:35:in `dispatch'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/bundler-2.5.14/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/bundler-2.5.14/lib/bundler/cli.rb:29:in `start'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/bundler-2.5.14/exe/bundle:28:in `block in <top (required)>'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/bundler-2.5.14/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/bundler-2.5.14/exe/bundle:20:in `<top (required)>'
        from /Users/tkomiya/.rbenv/versions/3.3.5/bin/bundle:25:in `load'
        from /Users/tkomiya/.rbenv/versions/3.3.5/bin/bundle:25:in `<main>'
```

**Comment by fumihumi** [comment]
I see.I misunderstood because I found out when I was updating the rbs_activesupport gem. Thank you for your comment.

**Comment by tk0miya** [comment]
Sorry for my very short response. Now I checked the code of RBS and post https://github.com/ruby/rbs/pull/2079 to fix this problem. Please follow the PR.

Thank you for reporting!
